units:
  chocx: 18
  chocy: 18
  chocspace: 2
  choczone: chocx + chocspace
  board_top: 2.2
  board_top_padding: chocy * 0.7
points:
  key:
    padding: chocy + chocspace
    spread: chocx + chocspace
  zones:
    main:
      rows:
        bottom:
          row_net: P2
        home:
          row_net: P5
        top:
          row_net: P8
        num:
          row_net: P21
        
      columns:
        outer:
          key.column_net: P1
        pinkey: 
          key.column_net: P3
        ring:       
          key.column_net: P4
          key.stagger: 4.7
        middle:
          key.column_net: P6
          key.stagger: 8.2 - 4.7
        index: 
          key.column_net: P7
          key.stagger: -6.8
        inner: 
          key.column_net: P9
          key.stagger: -3.5

    thumb_cluster_l:
      anchor:
        ref: main_inner_bottom
        shift: [-choczone, -choczone + 4]
        rotate: 0
      rows:
        key.row_net: P20
      columns:
        thumb_left:
          key.column_net: P4
          key.spread: chocx

    thumb_cluster_r:
      anchor:
        ref: main_inner_bottom
        shift: [chocx - 15,-chocy - 4]
        rotate: -30
      rows:
        key.row_net: P20
      columns:
        thumb_middle:
          key.column_net: P6
        thumb_right:
          key.column_net: P7
          key.spread: chocx + chocspace
          key.stagger: chocx -27
        thumb_top:
          key.column_net: P9
          key.spread: 0
          key.stagger: chocx + chocspace

pcbs:
  simple_split:
    template: kicad8
    outlines:
      main:
        outline: _combined_base
    footprints:
      # KEYS
      keys:
        what: switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          reversible: true
          hotswap: true
          choc_v2_support: false
          include_choc_v1_led_cutout_marks: true
          include_corner_marks: true
        adjust:
          rotate: 180

      diode:
        what: diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: -90
          shift: [-9, 0]

      rgb:
        what: led_sk6812mini-e
        where: true
        params:
          P1: VCC
          P2: "do_{{colrow}}"
          P3: GND
          P4: "di_{{colrow}}"
          reversible: true
        adjust:
          shift: [0, 4.65]


      # TOP BOARDS
      reset:
        what: reset_switch_smd_side
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [main_ring_top]
          shift: [chocx * 0.3, (chocy * board_top) + (board_top_padding * 0.5)]

      trrs:
        what: trrs
        where:
          ref: main_ring_top
          shift: [-(chocx * 0.3), (chocy * board_top) + (board_top_padding * 0.65)]
        params:
          A: GND
          B: GND
          C: P0
          D: VCC
          reverse: true
          symmetric: true

      mcu:
        what: promicro
        where:
          - ref: main_outer_top
            shift: [chocx / 2, chocy * board_top + 1]
        params:
          orientation: up

outlines:
  _base:
    - where: true
      what: rectangle
      size: [chocx + 4, chocy + 4]
      fillet: 2

  _pcb:
    - what: polygon
      operation: stack
      points:
        - ref: main_outer_top
          shift: [-(chocx / 2) - 2, 0]
        - ref: main_outer_top
          shift: [chocx * 2.8, 0]
        - ref: main_outer_top
          shift: [chocx * 2.8, (chocy * board_top) + board_top_padding]
        - ref: main_outer_top
          shift: [-(chocx / 2) - 2, (chocy * board_top) + board_top_padding]
      fillet: 2

  _hole_cover:
    - what: polygon
      operation: stack
      points:
        - ref: main_index_bottom
          shift: [0, 0]
        - ref: main_index_bottom
          shift: [chocx * 1.72, 0]
        - ref: main_index_bottom
          shift: [chocx * 1.72, -chocy * 1.6]
        - ref: main_index_bottom
          shift: [0, -chocy * 1.6]

  _combined_base:
    - name: _base
      operation: add
    - name: _pcb
      operation: add
    - name: _hole_cover
      operation: add

  _keys:
    - what: rectangle
      where: true
      size: [chocx-0.5,chocy-0.5]

  _keys_inner_cutout:
    - where: true
      what: rectangle
      size: [14, 14]
      
  _key_puller_holes:
    - name: _keys_inner_cutout
      operation: add
    - what: rectangle
      where: true
      size: [4, 17.8]
      operation: add
  
  view_keyboard_outline:
    - name: _combined_base
      operation: add
    - name: _keys
      operation: subtract

  # PRINTS
  print_keyboard_outline_inner_upper:
    - name: _combined_base
      operation: add
    - name: _key_puller_holes
      operation: subtract

  print_keyboard_outline_inner_lower:
    - name: _combined_base
      operation: add
    - name: _keys_inner_cutout
      operation: subtract
      
  print_base:
    - name: _combined_base

