#define EE_HANDS

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 120000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60
